# The following configurations need to be set as environment variables:
# - elasticsearch_api_base_url
# - github_user
# - github_access_token


# List of Github organizations to be cycled through and ingested
orgs:
 - usdot-jpo-ode
 - usdot-its-jpo-data-portal
 - VolpeUSDOT
 - usdot-jpo-sdcsdw

# List of individual repos to be ingested
individual_repos:
  # Test repo:
 - nickprice-bah/user_repo

sonar_health_metrics:
  - bugs 
  - new_bugs
  - reliability_rating
  - vulnerabilities
  - new_vulnerabilities
  - security_rating
  - code_smells
  - new_code_smells
  - sqale_rating
  - dupilicated_lines_density
  - lines_of_code
  - complexity
  - comments_lines_density
  - violations
  - new_violations

sonar_runner_path: /opt/sonar-runner/bin/sonar-runner
sonar_api_local_base_url: http://localhost:9000/api/resources