# List of Github orgs to be cycled through and ingested
orgs:
 - usdot-jpo-ode
 - usdot-its-jpo-data-portal
 - VolpeUSDOT
 - usdot-jpo-sdcsdw

sonar_health_metrics:
  - bugs 
  - new_bugs
  - reliability_rating
  - vulnerabilities
  - new_vulnerabilities
  - security_rating
  - code_smells
  - new_code_smells
  - sqale_rating
  - dupilicated_lines_density
  - lines_of_code
  - complexity
  - comments_lines_density
  - violations
  - new_violations

github_user: 
github_access_token: 

sonar_runner_path: /opt/sonar-runner/bin/sonar-runner
sonar_api_local_base_url: http://localhost:9000/api/resources

sqs_queue: 